### ISSUE TITLE
Replace custom Frontend with Vuetify

### ISSUE THREAD

**Issue by svenfinke** [otto-de/gitactionboard#127]
The current frontend is custom built and every feature - like the sidebar toggle - has to be created. This can easily lead to errors regarding different screen sizes, browser window ratios, etc... It also slows down the implementation of new features.

I'd like to switch to a frontend framework like vuetify. Using a framework like that comes with quite a few benefits:
- **many** pre-built components that can just be used
- consistent design
- easy adoption of screen sizes
Vuetify would be my choice as it implements the material design and it comes with a lot of easy to use components and helpers that make it really easy to implement different features.

**Comment by svenfinke** [comment]
I already started working on this. Here is a little glimpse on how it could look in the future (still WIP, that's why all cards are red right now ;) )
<img width="413" alt="Bildschirmfoto 2022-12-08 um 11 52 58" src="https://user-images.githubusercontent.com/564499/206431787-1d116bab-ed32-4e5e-b4f2-24fb4a98eb90.png">
<img width="720" alt="Bildschirmfoto 2022-12-08 um 11 52 50" src="https://user-images.githubusercontent.com/564499/206431795-e228e85a-3479-4651-8c58-d6971679b276.png">
<img width="1397" alt="Bildschirmfoto 2022-12-08 um 11 49 34" src="https://user-images.githubusercontent.com/564499/206431804-5b900cd9-fc03-4cc7-a387-399483723c6a.png">

**Comment by sumanmaity1234** [comment]
Hi @svenfinke, It's a nice idea. Please go ahead and create PR once you are done with the required changes :)
