### ISSUE TITLE
Show gitactionboard version number in ui

### ISSUE THREAD

**Issue by baztian** [otto-de/gitactionboard#162]
**Is your feature request related to a problem? Please describe.**
To me it's unclear which version is currently live. I always need to check in my container orchestrator to see which version is live.

**Describe the solution you'd like**
Show the version number of Gitactionboard (e.g. v3.0.5) somewhere in UI.

**Describe alternatives you've considered**
None

**Comment by sumanmaity1234** [comment]
It's a nice idea to display version number on the dashboard. Currently, I don't have bandwidth to work on it, if anyone else can pick it up then it'll be really nice. Otherwise maybe I can pick it up once I have some bandwidth.

@baztian do you want to pick it up?

**Comment by sumanmaity1234** [comment]
@baztian, With new version (v3.1.0) you'll be able to see the version number on dashboard. Have a look into the following sample screenshots in https://github.com/otto-de/gitactionboard/blob/main/doc
