### ISSUE TITLE
Add additional filter for Pull Request builds 

### ISSUE THREAD

**Issue by bennetelli** [otto-de/gitactionboard#216]
**Is your feature request related to a problem? Please describe.**
We are using the gitactionboard as part of our Daily Operations tasks. As someone who is responsible for the status of all of our pipelines, it would be great to add an additional filter for all Pull Request builds. Right now it's possible to filter green builds and show the red ones only. Unfortunately tools like dependabot are leading to some additional builds and this is getting confusing for the person who is doing the operations for the team.

**Describe the solution you'd like**
I would like to get an additional filter so the daily operations guy can get a quick overview of the status of all applications on the master branch.

**Comment by sumanmaity1234** [comment]
Hi @bennetelli, it's a nice idea to have more filters but instead of having just for **master** branch it'll nice to add possibility to filter any branch.

**Comment by bennetelli** [comment]
> Hi @bennetelli, it's a nice idea to have more filters but instead of having just for **master** branch it'll nice to add possibility to filter any branch (from UI).

yea, I am fine with it as well.

**Comment by bennetelli** [comment]
any updates on this issue? :)

**Comment by sumanmaity1234** [comment]
Hi @bennetelli, currently I am working in a different feature/improvement. Do you want to create a PR for this feature
