### ISSUE TITLE
runStatus does not support all the Github Run statuses, specific Waiting is missing

### ISSUE THREAD

**Issue by globaltopmedia** [otto-de/gitactionboard#484]
Workflows which are in the status Waiting will cause a java error as they are not part of the allowed enum.

1. Create a workflow requiring deployment approval (using the deployment protection rules). See https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
2. Run the workflow
3. Don't approve the run
4. Start the gitactionboard
5. Access the gitactionboard
6. Check the error log in docker
7. `Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `de.otto.platform.gitactionboard.adapters.service.job.RunStatus` from String "waiting": not one of the values accepted for Enum class: [queued, in_progress, completed]`
8. Check the workflow status in Github, it is set to "waiting"
9. Check the gitactionboard source code, backend/src/main/java/de/otto/platform/gitactionboard/adapters/service/job/RunStatus.java, waiting is not part of the enum

**Expected behavior**
Support for the "waiting" workflow status, but ideally all statuses as listed on https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28

**Comment by sumanmaity1234** [comment]
Got fixed as part of [v3.3.7](https://github.com/otto-de/gitactionboard/releases/tag/v3.3.7)
