### ISSUE TITLE
Workflow shows as failed, even if the latest workflow attempt of the job is successfully

### ISSUE THREAD

**Issue by globaltopmedia** [otto-de/gitactionboard#496]
**Describe the bug**
If a workflow job initially fails but a rerun of the same workflow job is successful, the workflow shows the state of the first attempt

**To Reproduce**

1. Run a workflow which should fail (due to wrong credentials).
2. gitactionboard shows the workflow as failed (correct), reflecting the state of the latest job.
3. resolve the reason why the workflow failed. (add correct credentials into github action secrets)
4. rerun the workflow job (attempt #2)
5. the attempt succeeds
6. gitactionboard shows the workflow still as failed (incorrect)

**Expected behavior**
gitactionboard should show the status of the latest attempt of a workflow job

**Comment by globaltopmedia** [comment]
Note the CCtray shows the evidence of the this issue as well

    {
        "name": "fake :: Build and Deploy :: release / release-to-dev",
        "activity": "Sleeping",
        "lastBuildStatus": "Failure",
        "lastBuildLabel": "23",
        "lastBuildTime": "2023-10-25T11:31:11.000Z",
        "webUrl": "https://github.com/fake/fake-api/actions/runs/66402497/job/182159058",
        "triggered event": "repository_dispatch"
    },
    
    the lastBuildTime is the datetime of the 1st attempt, not the 2nd one.
    
    Backgrounder https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

**Comment by sumanmaity1234** [comment]
Hi @globaltopmedia, could you please check your cache config? I just tried to reproduce it and it's working fine.

Until cache expires, it'll not fetch latest details from GitHub.
