### ISSUE TITLE
Running the docker Container

### ISSUE THREAD

**Issue by gtogbes** [otto-de/gitactionboard#52]
Hi it would be nice to have an example deployment in the README, using an organisation and or a USERNAME. Also a multi repo view example too would be appreciated.

**Comment by sumanmaity1234** [comment]
Hi @gtogbes, do you think something like the following would help
```sh
docker run \
--env REPO_OWNER_NAME=webpack \
--env REPO_NAMES=webpack-cli,webpack-dev-server \
-p 8080:8080 \
-it ottoopensource/gitactionboard:latest

```

**Comment by gtogbes** [comment]
yes exactly. thank you
