### ISSUE TITLE
Marked as phishing

### ISSUE THREAD

**Issue by EAlf91** [otto-de/gitactionboard#80]
**Describe the bug**
We recently moved our buildmonitor to be available from outside of the otto whitelist and got flagged as phishing website.

Firefox then showed a warning similar to the one below not only for this subdomain but also for the whole domain.

We're not quite sure how this happened and it doesn't seem to be a certificate issue as everything was up to date. Nontheless it might be worth investigating on that topic.

For now we restricted the monitor to internal traffic once again.

**Screenshots**

![image](https://user-images.githubusercontent.com/114851460/199240367-d5e2fa98-08c1-4e97-b3ba-a255b7f4e479.png)

**Comment by sumanmaity1234** [comment]
Hi @EAlf91, I don't think it is an issue with gitactionboard as gitactionboard doesn't comes with any SSL certificate.

It doesn't supports HTTPS by default. If you need HTTPS connection then you may need to add some sort of proxy (ex: [nginx](https://www.nginx.com/)).

Either way, please let us know if you find some issue in gitactionboard code, I will also try to investigate the issue.

Btw, are you using in-built login mechanism?

**Comment by EAlf91** [comment]
Hey @sumanmaity1234 Sorry, that was propably not correctly communicated from my side. The SSL Certificate was just wild guessing from our side but we're having it managed by aws so it was not an issue.


we initialize the service like this and use github oicd login:

```sudo docker run -p ${port}:${port} \
  --log-driver=awslogs --log-opt awslogs-group="${log_group_name}" \
  -e REPO_OWNER_NAME="${repo_owner_name}" \
  -e REPO_NAMES="${repo_names}" \
  -e GITHUB_OAUTH2_CLIENT_ID="${clientId}" \
  -e GITHUB_OAUTH2_CLIENT_SECRET="${clientSecret}" \
  -e SPRING_APPLICATION_JSON='{"server":{"forward-headers-strategy":"FRAMEWORK"}}' \
  --name build-monitor \
  -d \
  -it ottoopensource/gitactionboard:latest`
  
I think the main point for us is that since anyone could flag some site as phishing and it happened only with that one it might be worth investigating which criteria was met or lead to this site being flagged.

**Comment by sumanmaity1234** [comment]
HI @EAlf91, docker command looks good to me. I still don't think phishing issue has anything do with the docker image. It'll better to check the SSL certificate.

**Comment by EAlf91** [comment]
@sumanmaity1234 we checked the ssl certificates and they were fine and up to date. Since anyone could flag a website as phishing It might have happened by some automatic process or some scraper. Unfortunately the process of being flagged as phishing is not very transparent and we're not sure which criteria lead to this.

I think we can close this issue for now. Might fit better in a discussion topic rather than an issue as it was propably not an issue with the project itself.
